"""initial schema

Revision ID: 2ebe3d1b7081
Revises: 
Create Date: 2026-05-20 15:17:54.895222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ebe3d1b7081'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('BPT', 'PPT', 'CPT', 'others', name='racecategory'), nullable=False),
    sa.Column('custom_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'finished', name='racestatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runners',
    sa.Column('army_number', sa.String(length=32), nullable=False),
    sa.Column('rfid_tag', sa.String(length=64), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('registered', 'running', 'finished', 'disqualified', name='runnerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('army_number')
    )
    op.create_index(op.f('ix_runners_rfid_tag'), 'runners', ['rfid_tag'], unique=True)
    op.create_table('checkpoint_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('army_number', sa.String(length=32), nullable=False),
    sa.Column('checkpoint', sa.Enum('start', 'checkpoint1', 'checkpoint2', 'finish', name='checkpointname'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reader_id', sa.String(length=32), nullable=True),
    sa.Column('race_session_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['army_number'], ['runners.army_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['race_session_id'], ['race_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkpoint_records_army_number'), 'checkpoint_records', ['army_number'], unique=False)
    op.create_index(op.f('ix_checkpoint_records_race_session_id'), 'checkpoint_records', ['race_session_id'], unique=False)
    op.create_table('race_results',
    sa.Column('army_number', sa.String(length=32), nullable=False),
    sa.Column('race_session_id', sa.UUID(), nullable=False),
    sa.Column('rfid_tag', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkpoint1_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkpoint2_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finish_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_time_seconds', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['army_number'], ['runners.army_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['race_session_id'], ['race_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('army_number', 'race_session_id')
    )
    op.create_index(op.f('ix_race_results_race_session_id'), 'race_results', ['race_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_race_results_race_session_id'), table_name='race_results')
    op.drop_table('race_results')
    op.drop_index(op.f('ix_checkpoint_records_race_session_id'), table_name='checkpoint_records')
    op.drop_index(op.f('ix_checkpoint_records_army_number'), table_name='checkpoint_records')
    op.drop_table('checkpoint_records')
    op.drop_index(op.f('ix_runners_rfid_tag'), table_name='runners')
    op.drop_table('runners')
    op.drop_table('race_sessions')
    # ### end Alembic commands ###
