"""Update schema

Revision ID: a3f9ce18889a
Revises: 
Create Date: 2026-05-19 17:16:37.309941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f9ce18889a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkpoint_records', sa.Column('army_number', sa.String(length=32), nullable=False))
    op.add_column('checkpoint_records', sa.Column('race_session_id', sa.UUID(), nullable=True))
    op.drop_index('ix_checkpoint_records_runner_id', table_name='checkpoint_records')
    op.create_index(op.f('ix_checkpoint_records_army_number'), 'checkpoint_records', ['army_number'], unique=False)
    op.create_index(op.f('ix_checkpoint_records_race_session_id'), 'checkpoint_records', ['race_session_id'], unique=False)
    op.drop_constraint('checkpoint_records_runner_id_fkey', 'checkpoint_records', type_='foreignkey')
    op.create_foreign_key(None, 'checkpoint_records', 'race_sessions', ['race_session_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'checkpoint_records', 'runners', ['army_number'], ['army_number'], ondelete='CASCADE')
    op.drop_column('checkpoint_records', 'runner_id')
    op.add_column('runners', sa.Column('verified', sa.Boolean(), nullable=False))
    op.add_column('runners', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_runners_army_number', table_name='runners')
    op.drop_column('runners', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runners', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index('ix_runners_army_number', 'runners', ['army_number'], unique=True)
    op.drop_column('runners', 'verified_at')
    op.drop_column('runners', 'verified')
    op.add_column('checkpoint_records', sa.Column('runner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'checkpoint_records', type_='foreignkey')
    op.drop_constraint(None, 'checkpoint_records', type_='foreignkey')
    op.create_foreign_key('checkpoint_records_runner_id_fkey', 'checkpoint_records', 'runners', ['runner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_checkpoint_records_race_session_id'), table_name='checkpoint_records')
    op.drop_index(op.f('ix_checkpoint_records_army_number'), table_name='checkpoint_records')
    op.create_index('ix_checkpoint_records_runner_id', 'checkpoint_records', ['runner_id'], unique=False)
    op.drop_column('checkpoint_records', 'race_session_id')
    op.drop_column('checkpoint_records', 'army_number')
    # ### end Alembic commands ###
